"""create world nodes and hotspots

Revision ID: c96a8f8b1f2a
Revises: b7d3f5c32f91
Create Date: 2026-01-23 08:10:00.000000
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'c96a8f8b1f2a'
down_revision = 'b7d3f5c32f91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    json_type = sa.JSON().with_variant(postgresql.JSONB, 'postgresql')

    op.create_table('world_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('is_entry', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('camera_position', json_type, nullable=False),
    sa.Column('camera_target', json_type, nullable=False),
    sa.Column('camera_fov', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('environment', json_type, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_nodes_key'), 'world_nodes', ['key'], unique=True)

    op.create_table('world_hotspots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('position', json_type, nullable=False),
    sa.Column('normal', json_type, nullable=True),
    sa.Column('radius', sa.Float(), server_default=sa.text('0.35'), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('payload', json_type, nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['world_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'key', name='uq_world_hotspots_node_key')
    )
    op.create_index(op.f('ix_world_hotspots_node_id'), 'world_hotspots', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_hotspots_node_id'), table_name='world_hotspots')
    op.drop_table('world_hotspots')
    op.drop_index(op.f('ix_world_nodes_key'), table_name='world_nodes')
    op.drop_table('world_nodes')
    # ### end Alembic commands ###
