"""fix users is_active default

Revision ID: e2c1a6b9c7f4
Revises: c96a8f8b1f2a
Create Date: 2026-01-23 09:30:00.000000
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c1a6b9c7f4'
down_revision = 'c96a8f8b1f2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.Boolean(),
        server_default=sa.text('true'),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users',
        'is_active',
        existing_type=sa.Boolean(),
        server_default=sa.text('1'),
        existing_nullable=False
    )
    # ### end Alembic commands ###
